book dto, repository, query, controller and test created
Sarvenaz83/HarryPotterAPI pull request #12
Opened 2024-01-16 14:05 UTC by Markuslarsson95

2024-01-16 20:54 UTC, Sarvenaz83 approved these changes

2024-01-16 21:22 UTC, Sarvenaz83 requested changes

2024-01-16 21:22 UTC, Sarvenaz83 commented on Infrastructure/DatabaseContext/HarryPotterContext.cs
> +            string connectionString = "Server=(local)\\sqlexpress;Database=HarryPotter;Trusted_Connection=true;TrustServerCertificate = true;";
Den delen bör inte merga på development branch. det kommer tänker jag när andra pulla den.

2024-01-16 21:22 UTC, Sarvenaz83 commented on Infrastructure/DatabaseContext/HarryPotterContext.cs
> +            string connectionString = "Server=(local)\\sqlexpress;Database=HarryPotter;Trusted_Connection=true;TrustServerCertificate = true;";
@Markuslarsson95

2024-01-16 21:22 UTC, Sarvenaz83 commented on Infrastructure/DependencyInjection.cs
> +                var connectionString = "Server=(local)\\sqlexpress;Database=HarryPotter;Trusted_Connection=true;TrustServerCertificate=true;";
@Markuslarsson95 här också

2024-01-17 12:10 UTC, kevjo15 approved these changes
ser bra ut

2024-01-17 12:11 UTC, Sarvenaz83 approved these changes

2024-01-17 12:11 UTC, merged